---
title: "Iteration & List Columns"
author: "Amin Yakubu"
date: "10/30/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
```

```{r}
l = list(vec_numeric = 5:8,
         mat         = matrix(1:8, 2, 4),
         vec_logical = c(TRUE, FALSE),
         summary     = summary(rnorm(1000)))

l

l[[2]]
```

```{r}
df = data_frame(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

is.list(df)

df[[2]]
```

Function 

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}

```

WE CAN apply the function to our df

```{r}
mean_and_sd(df[[1]])
mean_and_sd(df[[2]])
```

Write a for loop!

```{r}

output[[1]] = mean_and_sd(df[[1]])
output[[2]] = mean_and_sd(df[[2]])
output[[3]] = mean_and_sd(df[[3]])
output[[4]] = mean_and_sd(df[[4]])


output = vector('list', length = 4)

for ( i in 1:4){
  output[[i]] = mean_and_sd(df[[i]])
}

output
```

### Map statements

Let's use a map statement. Let's replace the 'for' loop with 'map'

```{r}
output = map(df, mean_and_sd)
```

Let's try a different function

```{r}

output = map(df, median)

ouput = map(df, summary)
```


### map variant

```{r}
output = map_df(df, mean_and_sd)

output = map_dbl(df, median)

output = map_df(df, summary)
```

### code syntax

Be clear about arguments
```{r}
output = map(.x = df, ~ mean_and_sd(x = .x))
```

```{r}
read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  data_frame(title, stars, text)
}

```

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url, 1:5)

read_page_reviews(vec_urls[[1]]) # works


output = vector('list', length = 5)

for ( i in 1:5){
  output[[i]] = read_page_reviews(vec_urls[[i]])
}

output

```




```{r}
library(rnoaa)

weather = 
  meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


```{r}
weather_nest = 
  nest(weather, date:tmin)

## Alternatively 

weather_nest = weather %>% 
  group_by(name, id)
  nest
```

Look at List columns elements

```{r}
weather_nest$data[[1]] 
```

Fit a location specific regression

```{r}
lm(tmax ~ tmin, data = weather_nest$data[[1]] )
lm(tmax ~ tmin, data = weather_nest$data[[2]] )
```


WRite a function!!

```{r}
weather_lm = function(df){
  lm(tmax ~ tmin, data = df)
}
```

```{r}
weather_lm(df = weather_nest$data[[1]])
```

```{r}
output = map(weather_nest$data, weather_lm)
```


Save output as a new list column...

```{r}
weather_nest %>% 
  mutate(lm_resutls = map(data, weather_lm))
```










































